export const ENABLE_LOGGER = "ENABLE_LOGGER";
export const GOOGLE_CLIENT_ID = "GOOGLE_CLIENT_ID";
export const GOOGLE_CLIENT_SECRET = "GOOGLE_CLIENT_SECRET";
export const GOOGLE_REDIRECT_URI = "GOOGLE_REDIRECT_URI";
export const AUTH_SEVER_PORT = "AUTH_SERVER_PORT";
